name: Test Redistribute

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

env:
  UV_SYSTEM_PYTHON: 1

jobs:
  test-redistribute:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.10"
      # Needed to run tests
      - name: Setup uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.6"
          enable-cache: true
      - name: Verify uv is available
        run: uv --version
      - name: Install build dependencies
        run: pip install build
      - name: Build source distribution
        run: python -m build --sdist
      - name: Decompress source distribution
        run: |
          cd dist
          tar xvf fastapi_new*.tar.gz
      - name: Install test dependencies
        run: |
          cd dist/fastapi_new*/
          pip install -r requirements-tests.txt
      - name: Run source distribution tests
        run: |
          cd dist/fastapi_new*/
          bash scripts/test.sh
      - name: Build wheel distribution
        run: |
          cd dist
          pip wheel --no-deps fastapi_new*.tar.gz

  # https://github.com/marketplace/actions/alls-green#why
  test-redistribute-alls-green:  # This job does nothing and is only used for the branch protection
    if: always()
    needs:
      - test-redistribute
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
